//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PssEntities : DbContext
    {
        public PssEntities()
            : base("name=PssEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientsNewsletter> ClientsNewsletters { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Text> Texts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<HomePage> HomePages { get; set; }
        public virtual DbSet<HomeProject> HomeProjects { get; set; }
        public virtual DbSet<PageOwner> PageOwners { get; set; }
        public virtual DbSet<PortfolioPage> PortfolioPages { get; set; }
        public virtual DbSet<PortfolioPhoto> PortfolioPhotos { get; set; }
    }
}
