//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePage
    {
        public string ID { get; set; }
        public string PageTitle { get; set; }
        public string PageSubTitle { get; set; }
        public string ButtonText { get; set; }
        public string AdditionalTitle { get; set; }
        public string AdditionalSubtitle { get; set; }
    }
}
