//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeProject
    {
        public string ID { get; set; }
        public string ProjTitle { get; set; }
        public string ProjSubtitle { get; set; }
        public string ProjImgPath { get; set; }
    }
}
