//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Mail { get; set; }
        public System.DateTime SessionDate { get; set; }
        public string PhoneNumber { get; set; }
        public int SessionTypeID { get; set; }
        public int SessionStatusID { get; set; }
        public string IP { get; set; }
        public System.DateTime RequestDate { get; set; }
    }
}
