//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSSCMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioPhoto
    {
        public int ID { get; set; }
        public bool IfActual { get; set; }
        public string ImgPath { get; set; }
        public string ImgDescription { get; set; }
    }
}
